# Generated by Django 5.0.6 on 2024-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('A', 'Accept'), ('R', 'Reject')], default='S', max_length=2),
        ),
    ]
